app = "my-flask-backend"  # Use a valid name here
primary_region = "cdg"    # I see you're using Paris region

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "5000"