# app/blueprints/reports/utils.py
import os
import requests
import json
import traceback # Import traceback for better error logging
import pandas as pd # Import pandas for checking types if needed
import numpy as np # Import numpy for checking types if needed

# --- الدوال الحالية للتقرير القالب (تم الإصلاح) ---
def generate_english_report(model_summary):
    """Generates a basic template-based English report."""
    # Ensure model_summary is a string
    summary_str = str(model_summary) if model_summary else "No model summary provided."
    report = f"""
## Econometric Analysis Report (Template Generated)

### 1. Executive Summary
This report details an econometric analysis based on the user-provided data...

### 2. Model Specification and Results
**Model Summary Output:**

{summary_str}


### 3. Interpretation of Results (Basic)
- **Model Fit:** Check R-squared values...
- **Coefficient Significance:** Check p-values (typically < 0.05)...
- **Diagnostic Tests (if available in summary):** Check Durbin-Watson etc...

### 4. Policy Implications (Generic)
Based on significant coefficients, potential policy implications can be inferred...

### 5. Conclusion
The analysis provides a quantitative framework... interpret with theory and context.

---
*Report generated by DataNomics Platform.*
"""
    return report.strip()


def generate_arabic_report(model_summary):
    """Generates a basic template-based Arabic report."""
    # Ensure model_summary is a string
    summary_str = str(model_summary) if model_summary else "لم يتم تقديم ملخص للنموذج."
    report = f"""
## تقرير تحليلي اقتصادي (قالب أساسي)

### ١. الملخص التنفيذي
يقدم هذا التقرير تحليلاً اقتصادياً قياسياً...

### ٢. مواصفات النموذج والنتائج
**ملخص مخرجات النموذج:**

{summary_str}


### ٣. تفسير النتائج (أساسي)
- **جودة التوفيق:** انظر إلى قيم R-squared...
- **الدلالة الإحصائية:** انظر إلى p-values (عادة < 0.05)...
- **الاختبارات التشخيصية (إن وجدت بالملخص):** انظر إلى Durbin-Watson إلخ...

### ٤. الآثار المترتبة على السياسات (عامة)
بناءً على المعاملات ذات الدلالة، يمكن استنتاج آثار على السياسات...

### ٥. الخلاصة
يوفر التحليل إطارًا كميًا... يجب التفسير في سياق النظرية.

---
*تم إنشاؤه بواسطة منصة DataNomics.*
"""
    return report.strip()
# --- (نهاية الإصلاح) ---


# --- (جديد) دالة مساعدة لتنسيق نتائج الاختبارات ---
def format_diagnostics_for_prompt(diagnostics_results=None, post_test_result=None):
    """Formats diagnostic test results into a readable string for the AI prompt."""
    formatted_string = ""
    found_diagnostics = False

    # Format automatic diagnostics (list of dicts)
    if isinstance(diagnostics_results, list) and diagnostics_results:
        formatted_string += "\n\n**Automatic Diagnostic Test Results:**\n"
        count = 0
        for test in diagnostics_results:
            # Ensure test is a dictionary
            if not isinstance(test, dict): continue

            name = test.get('name', 'Unnamed Test')
            stat = test.get('statistic', 'N/A')
            pval = test.get('p_value', 'N/A')
            interp = test.get('interpretation', '')

            # Format p-value and statistic nicely if they are numbers
            try:
                pval_str = f"{float(pval):.4f}" if pval not in [None, 'N/A', ''] else 'N/A'
            except (ValueError, TypeError):
                pval_str = str(pval) # Keep as string if conversion fails

            try:
                stat_str = f"{float(stat):.4f}" if stat not in [None, 'N/A', ''] else 'N/A'
            except (ValueError, TypeError):
                stat_str = str(stat) # Keep as string

            formatted_string += f"- **{name}:** Stat={stat_str}, P-Value={pval_str}. *Interpretation:* {interp}\n"
            count += 1
        if count > 0: found_diagnostics = True


    # Format manually run post-test result (dict)
    if isinstance(post_test_result, dict) and post_test_result:
        formatted_string += "\n**Specific Post-Estimation Test Result:**\n"
        name = post_test_result.get('name', post_test_result.get('test_name', 'Specific Test'))
        stat = post_test_result.get('statistic', post_test_result.get('stat', 'N/A'))
        pval = test.get('p_value', 'N/A')
        interp = post_test_result.get('interpretation', '')
        details = post_test_result.get('details', post_test_result.get('formatted_results', ''))
        html = post_test_result.get('html_table', '')

        # Format p-value and statistic
        try:
            pval_str = f"{float(pval):.4f}" if pval not in [None, 'N/A', ''] else 'N/A'
        except (ValueError, TypeError):
            pval_str = str(pval)

        try:
            stat_str = f"{float(stat):.4f}" if stat not in [None, 'N/A', ''] else 'N/A'
        except (ValueError, TypeError):
            stat_str = str(stat)

        formatted_string += f"- **{name}:**"
        if stat_str != 'N/A': formatted_string += f" Stat={stat_str}"
        if pval_str != 'N/A': formatted_string += f", P-Value={pval_str}"
        formatted_string += f". *Interpretation:* {interp}\n"

        # Add details (if not HTML table)
        if details and isinstance(details, str) and not html:
             # Basic cleaning of details string if needed
             cleaned_details = '\n'.join(line.strip() for line in details.strip().splitlines() if line.strip())
             formatted_string += f"  Details:\n```\n{cleaned_details}\n```\n"
        # Note about HTML table if present
        elif html:
             formatted_string += f"  (Detailed results were provided in an HTML table format).\n"
        found_diagnostics = True


    if not found_diagnostics:
        formatted_string = "\n\n**Diagnostic Tests:** No specific diagnostic results provided or tests were not applicable.\n"

    return formatted_string
# --- (نهاية الإضافة) ---


# --- (تعديل) دالة استدعاء Gemini API ---
def call_gemini_api(prompt, model_summary, diagnostics_results=None, post_test_result=None):
    """Calls the Gemini API with model summary and formatted diagnostic results."""

    api_key = os.environ.get('GEMINI_API_KEY')
    if not api_key:
         print("CRITICAL ERROR: GEMINI_API_KEY not found in environment variables. Cannot call Gemini API.")
         raise ValueError("AI configuration error: API key for the generative model is missing.")

    # --- (هذا هو الإصلاح) ---
    # "gemini-pro" و "gemini-1.5-flash-001" غير مدعومين على v1beta بهذا الشكل
    # سنستخدم "gemini-1.5-pro-latest" وهو الموديل القياسي لـ v1beta
    model_name = "gemini-1.5-pro-latest" 
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={api_key}"
    # --- (نهاية الإصلاح) ---


    # --- Format diagnostics ---
    formatted_diagnostics = format_diagnostics_for_prompt(diagnostics_results, post_test_result)
    # --- ---

    summary_str = str(model_summary) if model_summary else "No model summary provided."

    full_prompt = f"{prompt}\n\n"
    full_prompt += f"**Model Summary Output:**\n```\n{summary_str}\n```\n"
    full_prompt += formatted_diagnostics

    payload = {
        "contents": [{"parts": [{"text": full_prompt}]}],
        "generationConfig": {
            "temperature": 0.6, 
            "maxOutputTokens": 4096,
            "topP": 0.95,
            "topK": 40
        },
    }

    print("\n--- Sending Prompt to Gemini ---") 
    print(full_prompt[:500] + "...")
    print("------\n")

    try:
        response = requests.post(url, json=payload, headers={"Content-Type": "application/json"}, timeout=120) 
        response.raise_for_status() 

        result = response.json()

        if 'candidates' not in result or not result['candidates']:
             prompt_feedback = result.get('promptFeedback', {})
             block_reason = prompt_feedback.get('blockReason', 'Unknown')
             safety_ratings = prompt_feedback.get('safetyRatings', [])
             error_message = f"Error: AI model did not return candidates. Reason: {block_reason}."
             if safety_ratings:
                 error_message += f" Safety Ratings: {json.dumps(safety_ratings)}"
             print(f"Gemini Error: {error_message}")
             return error_message 

        candidate = result['candidates'][0]

        finish_reason = candidate.get('finishReason', 'UNKNOWN')
        if finish_reason not in ['STOP', 'MAX_TOKENS']:
             safety_ratings = candidate.get('safetyRatings', [])
             block_reason_detail = f"Finish Reason: {finish_reason}."
             if safety_ratings:
                 block_reason_detail += f" Safety Ratings: {json.dumps(safety_ratings)}"
             print(f"Warning: Gemini generation issue: {block_reason_detail}")

        content = candidate.get('content', {})
        parts = content.get('parts', [{}])
        generated_text = parts[0].get('text', '') if parts else ''

        if not generated_text:
             print("Warning: Gemini returned an empty text response.")
             if finish_reason != 'STOP':
                 return f"Error: AI model returned an empty response. Possible reason: {finish_reason}."
             else:
                 return "AI model returned an empty response."


        return generated_text.strip() # Return cleaned text

    except requests.exceptions.Timeout:
        print("Error: Gemini API request timed out after 120 seconds.")
        return "Error: The request to the AI model timed out (120s). The model might be taking too long or there's a network issue. Please try again."
    except requests.exceptions.RequestException as e:
        error_details = str(e)
        status_code = e.response.status_code if e.response is not None else 'N/A'
        response_text = e.response.text if e.response is not None else 'N/A'
        # --- (إصلاح) إظهار الخطأ الحقيقي للمستخدم ---
        # 1. طباعة الخطأ الكامل في السيرفر
        print(f"Error: Gemini API request failed: Status={status_code}, Error={error_details}, Response Body={response_text[:500]}")
        # 2. إرجاع رسالة خطأ واضحة
        try:
            # محاولة قراءة رسالة الخطأ من Gemini
            error_json = json.loads(response_text)
            user_error = error_json.get('error', {}).get('message', f"AI Error (Status: {status_code})")
            return f"Error: {user_error}"
        except json.JSONDecodeError:
             return f"Error: AI report generation failed (Status: {status_code}). Check server logs for details."
        # --- (نهاية الإصلاح) ---
    except (KeyError, IndexError, json.JSONDecodeError) as e:
        print(f"Error: Failed to parse Gemini API response: {e}")
        raw_response = "N/A"
        if 'response' in locals() and hasattr(response, 'text'):
            raw_response = response.text
        print("Raw Response:", raw_response[:500])
        return "Error: Failed to parse the AI model's response. The structure might be unexpected."
    except Exception as e: # Catch-all for other unexpected errors
        print(f"Unexpected error during Gemini API call:")
        traceback.print_exc() # Print full traceback
        return f"Error: An unexpected error occurred during AI report generation. Please check server logs."
# --- (نهاية التعديل) ---


# --- (تعديل) دوال توليد التقرير الذكي ---
def generate_gemini_english_report(model_summary, diagnostics_results=None, post_test_result=None):
    """Generates a professional English report using the Gemini API, including diagnostics."""

    prompt = """
    As an expert econometrician, write a comprehensive and professional analytical report based on the provided **Model Summary Output** AND **Diagnostic Test Results**. Structure the report with the following numbered sections:

    1.  **Executive Summary:** Briefly summarize the main findings about variable relationships AND the overall validity/reliability of the model based on diagnostics.
    2.  **Model Interpretation:** Analyze coefficients (magnitude, sign, significance p<0.05), and overall fit (R-squared/Pseudo R-sq). Explain significant variables in economic context.
    3.  **Diagnostic Assessment:**
        * **Critically Evaluate** the provided 'Automatic Diagnostic Test Results' and 'Specific Post-Estimation Test Result'.
        * For each **FAILED** diagnostic test (e.g., p<=0.05 for Breusch-Pagan, Breusch-Godfrey, Jarque-Bera; VIF > 10; Failed Stability), clearly state the **problem detected** (e.g., "Heteroskedasticity detected") and its primary **implication** (e.g., "Standard errors and p-values are unreliable").
        * For **PASSED** tests, briefly confirm model adequacy for that assumption (e.g., "No significant autocorrelation found").
        * Explicitly mention results of key decision tests like Hausman (for FE vs RE choice), Johansen/Bounds test (for cointegration).
    4.  **Model Reliability & Trustworthiness:** Based *solely* on the diagnostic assessment in section 3, provide a concise verdict. Is the model statistically reliable for inference as is? (e.g., "Reliable", "Tentatively reliable, but caution needed due to...", "Unreliable due to multiple failures").
    5.  **Policy Implications:** Suggest 2-3 specific, actionable policy implications derived from the significant model coefficients, *BUT* preface these with a statement reflecting the model's reliability (e.g., "Assuming the model is reliable...", or "If the model's issues were addressed, the results suggest..."). Do NOT provide implications if the model is deemed unreliable.
    6.  **Limitations & Recommendations:** Briefly mention standard limitations (omitted variables etc.) AND provide specific **recommendations for improvement** based directly on the **diagnostic failures** identified in section 3 (e.g., "Use Robust Standard Errors", "Consider adding lags", "Check for structural breaks", "Use a different model like VECM").

    **IMPORTANT:** Ensure the diagnostic findings directly influence the conclusions in sections 1, 4, 5, and 6. Use clear, professional language. Format using Markdown.
    """
    return call_gemini_api(prompt, model_summary, diagnostics_results, post_test_result)


def generate_gemini_arabic_report(model_summary, diagnostics_results=None, post_test_result=None):
    """Generates a professional Arabic report using the Gemini API, including diagnostics."""

    prompt = """
    بصفتك خبيرًا متميزًا في الاقتصاد القياسي، قم بإعداد تقرير تحليلي احترافي وشامل باللغة العربية الفصحى، مستندًا إلى **ملخص النموذج الإحصائي** المرفق و **نتائج الاختبارات التشخيصية** المرفقة. يجب أن يكون التقرير منظمًا وفق الأقسام المرقمة التالية:

    ١.  **الملخص التنفيذي:** قدم ملخصًا موجزًا للنتائج الرئيسية حول علاقات المتغيرات **ومدى صحة وموثوقية النموذج** بناءً على الاختبارات التشخيصية.
    ٢.  **تفسير النموذج:** حلل المعاملات (الحجم، الإشارة، الدلالة الإحصائية p<0.05)، وجودة التوفيق الكلية (R-squared/Pseudo R-sq). اشرح المتغيرات ذات الدلالة في سياق اقتصادي واضح.
    ٣.  **تقييم الاختبارات التشخيصية:**
        * **قيّم بشكل نقدي** 'نتائج الاختبارات التشخيصية التلقائية' و 'نتيجة الاختبار البعدي المحدد' المرفقة.
        * لكل اختبار **فشل** (مثل: p<=0.05 لاختبارات Breusch-Pagan, Breusch-Godfrey, Jarque-Bera؛ أو VIF > 10؛ أو فشل اختبار الاستقرار)، اذكر بوضوح **المشكلة التي تم اكتشافها** (مثال: "تم اكتشاف مشكلة عدم ثبات التباين") و **أثرها الرئيسي** (مثال: "الأخطاء المعيارية وقيم P-value غير موثوقة").
        * للاختبارات التي **نجحت**، أكد بإيجاز كفاءة النموذج فيما يتعلق بهذا الافتراض (مثال: "لم يتم العثور على ارتباط ذاتي معنوي").
        * اذكر صراحة نتائج اختبارات القرار الهامة مثل Hausman (لاختيار FE مقابل RE)، واختبارات التكامل المشترك Johansen/Bounds (إن وجدت).
    ٤.  **موثوقية النموذج وجدارة الثقة:** بناءً *فقط* على التقييم التشخيصي في القسم ٣، قدم حكمًا موجزًا. هل النموذج موثوق إحصائيًا للاستدلال كما هو؟ (مثال: "موثوق"، "موثوق مبدئيًا مع ضرورة الحذر بسبب..."، "غير موثوق بسبب فشل اختبارات متعددة").
    ٥.  **الآثار المترتبة على السياسات:** اقترح 2-3 توصيات سياسات محددة وقابلة للتطبيق مستمدة من معاملات النموذج ذات الدلالة الإحصائية، *ولكن* ابدأ هذه التوصيات بعبارة تعكس موثوقية النموذج (مثال: "بافتراض أن النموذج موثوق..."، أو "إذا تم معالجة مشاكل النموذج، تشير النتائج إلى..."). **لا تقدم** توصيات إذا اعتبر النموذج غير موثوق.
    ٦.  **القيود والتوصيات:** اذكر بإيجاز القيود المعتادة (المتغيرات المحذوفة، إلخ) **وقدم توصيات محددة للتحسين** بناءً مباشرة على **الاختبارات التشخيصية الفاشلة** المحددة في القسم ٣ (مثال: "استخدام الأخطاء المعيارية المصححة Robust Standard Errors", "النظر في إضافة فترات إبطاء", "التحقق من وجود انقطاعات هيكلية", "استخدام نموذج مختلف مثل VECM").

    **هام:** تأكد من أن نتائج الاختبارات التشخيصية تؤثر بشكل مباشر على الاستنتاجات في الأقسام ١ و ٤ و ٥ و ٦. استخدم لغة عربية فصحى واضحة واحترافية. قم بتنسيق الإجابة باستخدام Markdown.
    """
    return call_gemini_api(prompt, model_summary, diagnostics_results, post_test_result)
# --- (نهاية التعديل) ---