import os
import requests
import json

# app/blueprints/reports/utils.py

def generate_english_report(model_summary):
    """
    Dynamically generates a professional English report.
    """
    # The f""" string was correctly opened but never closed with another """.
    # This has been fixed.
    report = f"""
## Econometric Analysis Report (AI Generated)

### 1. Executive Summary

This report details an econometric analysis based on the user-provided data. The primary objective was to model the relationships between the selected economic variables. The analysis indicates statistically significant findings, providing valuable insights for economic interpretation and policy-making.

### 2. Model Specification and Results

The core of this analysis is the fitted econometric model. Below is the detailed summary output from the statistical software, which includes coefficient estimates, standard errors, t-statistics, and p-values.

**Model Summary Output:**
```
{model_summary}
```

### 3. Interpretation of Results

The model summary provides a wealth of information. Key takeaways include:
- **Model Fit:** The R-squared and Adjusted R-squared values indicate the proportion of variance in the dependent variable(s) that is predictable from the independent variable(s).
- **Coefficient Significance:** Variables with p-values less than 0.05 are typically considered statistically significant, implying a real relationship with the dependent variable.
- **Diagnostic Tests:** Statistics like the Durbin-Watson test help check for issues such as autocorrelation, ensuring the reliability of the model.

### 4. Policy Implications

Based on the model's findings, several policy implications can be inferred. For instance, if an independent variable like 'Government Spending' has a significant positive coefficient on 'GDP', it suggests that fiscal stimulus could be an effective tool for economic growth. Conversely, a significant negative coefficient on 'Interest Rate' would support conventional monetary policy theories.

### 5. Conclusion

The analysis provides a robust quantitative framework for understanding the economic dynamics at play. While the model is a powerful tool, its results should be interpreted in the context of economic theory and real-world conditions.

---
*This report was auto-generated by Fawzy's Econometrics Platform.*
"""
    return report.strip()


def generate_arabic_report(model_summary):
    """
    Dynamically generates a professional Arabic report.
    """
    report = f"""
## تقرير تحليلي اقتصادي (مدعوم بالذكاء الاصطناعي)

### ١. الملخص التنفيذي

يقدم هذا التقرير تحليلاً اقتصادياً قياسياً مفصلاً بناءً على البيانات المقدمة من المستخدم. كان الهدف الأساسي هو نمذجة العلاقات بين المتغيرات الاقتصادية المختارة. تشير النتائج إلى دلالة إحصائية مهمة، مما يوفر رؤى قيمة للتفسير الاقتصادي وصنع السياسات.

### ٢. مواصفات النموذج والنتائج

جوهر هذا التحليل هو النموذج الاقتصادي القياسي الذي تم تقديره. فيما يلي ملخص المخرجات التفصيلية من البرنامج الإحصائي، والذي يتضمن تقديرات المعاملات، والأخطاء المعيارية، وإحصاءات t، والقيم الاحتمالية.

**ملخص مخرجات النموذج:**
```
{model_summary}
```

### ٣. تفسير النتائج

يقدم ملخص النموذج معلومات غنية. تشمل النقاط الرئيسية ما يلي:
- **جودة توفيق النموذج:** تشير قيم R-squared و Adjusted R-squared إلى نسبة التباين في المتغير(ات) التابعة التي يمكن التنبؤ بها من المتغير(ات) المستقلة.
- **الدلالة الإحصائية للمعاملات:** تعتبر المتغيرات ذات القيم الاحتمالية (p-values) الأقل من 0.05 ذات دلالة إحصائية، مما يعني وجود علاقة حقيقية مع المتغير التابع.
- **الاختبارات التشخيصية:** تساعد إحصاءات مثل اختبار Durbin-Watson في التحقق من مشكلات مثل الارتباط الذاتي، مما يضمن موثوقية النموذج.

### ٤. الآثار المترتبة على السياسات

بناءً على نتائج النموذج، يمكن استنتاج العديد من الآثار المترتبة على السياسات. على سبيل المثال، إذا كان لمتغير مستقل مثل "الإنفاق الحكومي" معامل إيجابي ذو دلالة على "الناتج المحلي الإجمالي"، فهذا يشير إلى أن التحفيز المالي يمكن أن يكون أداة فعالة للنمو الاقتصادي.

### ٥. الخلاصة

يوفر التحليل إطارًا كميًا قويًا لفهم الديناميكيات الاقتصادية. على الرغم من أن النموذج أداة قوية، يجب تفسير نتائجه في سياق النظرية الاقتصادية والظروف الواقعية.

---
*تم إنشاء هذا التقرير تلقائيًا بواسطة منصة فوزي للاقتصاد القياسي.*
"""
    return report.strip()







# app/blueprints/reports/utils.py


def call_gemini_api(prompt, model_summary):
    """
    Calls the Gemini API to generate text based on a prompt and model summary.
    """
    api_key = os.environ.get('GEMINI_API_KEY')
    if not api_key:
        raise ValueError("GEMINI_API_KEY not found in environment variables.")

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key={api_key}"
    
    # The full prompt combines the instructions with the actual model results
    full_prompt = f"{prompt}\n\nHere is the model summary:\n```\n{model_summary}\n```"
    
    payload = {
        "contents": [{
            "parts": [{"text": full_prompt}]
        }]
    }

    try:
        response = requests.post(url, json=payload, headers={"Content-Type": "application/json"})
        response.raise_for_status() # Raises an HTTPError for bad responses (4xx or 5xx)
        
        result = response.json()
        
        # Safely extract the text content
        candidate = result.get('candidates', [{}])[0]
        content_part = candidate.get('content', {}).get('parts', [{}])[0]
        generated_text = content_part.get('text', 'Error: Could not extract generated text from API response.')
        
        return generated_text

    except requests.exceptions.RequestException as e:
        # Handle network errors, timeouts, etc.
        return f"Error: API request failed. {str(e)}"
    except (KeyError, IndexError, json.JSONDecodeError):
        # Handle malformed JSON response from the API
        return "Error: Failed to parse the API response. The response may be malformed."


def generate_gemini_english_report(model_summary):
    """
    Generates a professional English report using the Gemini API.
    """
    prompt = """
    As an expert econometrician, write a comprehensive and professional analytical report based on the provided model summary. Structure the report with the following sections:
    1.  **Executive Summary:** A brief overview of the findings.
    2.  **Model Interpretation:** Analyze the model's coefficients, R-squared, and key statistics. Explain what the significant variables mean in an economic context.
    3.  **Diagnostic Checks:** Briefly mention the implications of tests like Durbin-Watson (autocorrelation) if present in the summary.
    4.  **Policy Implications:** Based on the results, suggest 2-3 potential policy implications.
    5.  **Limitations:** Mention potential limitations of this model (e.g., omitted variables, sample size).
    
    Be clear, concise, and use professional language.
    """
    return call_gemini_api(prompt, model_summary)


def generate_gemini_arabic_report(model_summary):
    """
    Generates a professional Arabic report using the Gemini API.
    """
    prompt = """
    بصفتك خبيرًا في الاقتصاد القياسي، قم بكتابة تقرير تحليلي احترافي وشامل بناءً على ملخص النموذج الإحصائي المرفق. يجب أن يتضمن التقرير الأقسام التالية:
    ١. **الملخص التنفيذي:** نظرة عامة موجزة على النتائج الرئيسية.
    ٢. **تفسير النموذج:** قم بتحليل معاملات النموذج، وقيمة R-squared، والإحصاءات الرئيسية. اشرح معنى المتغيرات ذات الدلالة الإحصائية في سياق اقتصادي.
    ٣. **الاختبارات التشخيصية:** اذكر بإيجاز دلالات الاختبارات مثل Durbin-Watson (الارتباط الذاتي) إذا كانت موجودة في الملخص.
    ٤. **الآثار على السياسات:** بناءً على النتائج، اقترح 2-3 توصيات للسياسات العامة.
    ٥. **قيود التحليل:** اذكر القيود المحتملة للنموذج (مثل المتغيرات المحذوفة، حجم العينة).

    اكتب بوضوح وإيجاز وبلغة احترافية.
    """
    return call_gemini_api(prompt, model_summary)